### ISSUE TITLE
Launching Crash : Duplicated Mods

### ISSUE THREAD

**Issue by realbun5** [JadedPacks/Agrarian-Skies#1]
## The Bug/Crash
Not sure if this counts as a bug or a crash, but I will put this in the crash section because this "crash" makes you unable to play and it happened on launching.
It's actually when I started the game up, I launched minecraft through twitch and I got this error, I don't know if this counts as a crash, but I will.
![image](https://user-images.githubusercontent.com/23720832/55209919-7ad4c280-5217-11e9-9108-a5ec43db902f.png)
I tried deleting the profile and reinstalling it, didn't work.

I went to the logs, found in the last 5 lines that the mods are duplicated, I went and check the location but found nothing duplicated. Take this Aroma1997Core as an example.
![image](https://user-images.githubusercontent.com/23720832/55210069-59c0a180-5218-11e9-9549-1926962eaa37.png)

## Logs

* Bug/Crash Log: https://pastebin.com/bJe2vrBY

## Client Information

* Modpack Version: 4.0.0
* Server/LAN/Single Player: Single Player
* OS : Windows 10
* RAM : 8GB, Allocated 5GB of RAM into Minecraft

**Comment by lays24mc** [comment]
Same problem with Server

**Comment by ghost** [comment]
Think this may be an issue with JadedLibs. I did a derpie probably xD

**Comment by ghost** [comment]
Fixed as of 4.0.1 (Coming later today)
