### ISSUE TITLE
Suggestion: Add a rainmaker to one of the early quests

### ISSUE THREAD

**Issue by Hillgrove** [JadedPacks/Agrarian-Skies#16]
been waiting in-game now for 5 concurrent days for it to rain.. I can't really progress before I have water.

Maybe add a single rainmaker (single use) for one of the early quests?

I havn't use the one provided by Forestry (which is in the pack) before, but if it isn't single use then maybe something like the one in this mod: 

https://www.curseforge.com/minecraft/mc-mods/rainmaker

it's simple to use, and single use only. Place down, and it rains.

**Comment by ghost** [comment]
This doesn't exist in 1.6.4 sadly D:
