### ISSUE TITLE
Quest reward Spiked Pick cannot be repaired

### ISSUE THREAD

**Issue by Hillgrove** [JadedPacks/Agrarian-Skies#17]
It cannot be repaired as it's head is made of Cactus. Cactus has been disabled as a Tinker's Construct material in the modpack.

**Comment by ghost** [comment]
Is this the "Writing Pick", or "Pick of Tears"

**Comment by Hillgrove** [comment]
now that I try to find the quest I got it from, it dawns on me that the pick might have been either a drop or an item from a reward bag... I can't find the quest at least.
