### ISSUE TITLE
Server Crash After updating to 4.0.5 from 3.1.4

### ISSUE THREAD

**Issue by RyabDev** [JadedPacks/Agrarian-Skies#18]
## Steps to Reproduce

1.Have a server running 3.1.4 Updated it to 4.0.5
2.All I did was deleted the Mods and Config Folders and replaced them from the 4.0.5 zip

The Server is running on linux though I know this has nothing to due with it as it worked before updating the pack

## Logs

* Crash Log:https://pastebin.com/ZnwS8ygC

## Client Information

* Modpack Version: 4.0.5
* Server/LAN/Single Player:Server Crash

**Comment by ghost** [comment]
Heyhey,

Can you post the "fml-server-latest.log" file please =] Can't work out the missing mod based on crash report (1.6.4 is very... unhelpful)

**Comment by RyabDev** [comment]
There is no fml-server-latest.log file though there is a  ForgeModLoader-server-0.log file https://pastebin.com/ZaRPuLkD

**Comment by ghost** [comment]
Delete "Zans Minimap" from mods directory, and try again.

**Comment by RyabDev** [comment]
Nope still getting the crash

**Comment by ghost** [comment]
Post the fml log

**Comment by RyabDev** [comment]
https://pastebin.com/CCnrfQfY

**Comment by ghost** [comment]
Hey, can you delete both the minimap and "jaded libs" again :P

**Comment by RyabDev** [comment]
now It worked

**Comment by RyabDev** [comment]
How does removing Jaded Libs effect the pack

**Comment by ghost** [comment]
Its simply used to download additional mods, that we can't distribute as part of the main pack due to CurseForge regulations.

**Comment by RyabDev** [comment]
Also is it intended that in the Morvy Cottage map there is no longer a starting chest which forces the player to wait for a tree to grow

**Comment by ghost** [comment]
It was actually intended that the tree was already grown. I may have to look into this =]
