### ISSUE TITLE
Hoppers cannot be crafted with aluminium in multiplayer

### ISSUE THREAD

**Issue by RyabDev** [JadedPacks/Agrarian-Skies#19]
## Bug Report

Attempting to craft a hopper using the aluminum recipe does not allow you to craft it

## Steps to Reproduce (for bugs)

1.Join the pack on a server 
2.Attempt to craft a hopper with aluminum as shown in NEI
3.Video: https://youtu.be/M1B7VR3vB8g

I attempted to reload the MT scripts with /MT Reload did not help

## Client Information

* Modpack Version:4.0.5
* Server/LAN/Single Player:Server

**Comment by ghost** [comment]
Does the server have the same scripts uploaded to it? Seems like the server doesn't have the same ones as the client.

**Comment by RyabDev** [comment]
Both are running the latest 4.0.5 and I dont see a scripts folder in either instance like later versions of MT so i'm guessing it the cfg files in ./config/minetweaker/

**Comment by ghost** [comment]
It is indeed.

**Comment by RyabDev** [comment]
Same exact files No idea why thats happening

**Comment by ghost** [comment]
Any chance you can poke me on the Jaded Packs discord? :)

**Comment by RyabDev** [comment]
sure could I get a link

**Comment by ghost** [comment]
https://discord.gg/bkyMbv2

**Comment by ghost** [comment]
Cannot replicate using a fresh install of the pack.
