### ISSUE TITLE
Unable to start modpack with JadedLibs installed

### ISSUE THREAD

**Issue by Sir-Will** [JadedPacks/Agrarian-Skies#21]
Getting this error when JadedLibs is installed, removing the mod allows me to start the modpack without issues.
![](https://i.imgur.com/jhVXqR2.jpg)
[ForgeModLoader-client-0.log](https://github.com/JadedPacks/Agrarian-Skies/files/3486551/ForgeModLoader-client-0.log)

**Comment by ghost** [comment]
Hopefully fixed as of https://github.com/JadedPacks/Agrarian-Skies/commit/e2dfff3c7f37b160c3bf598db8d46bb6e5660230.

If this issue persists let me know and I'll re-open and see if there's any other fix I need to do.

**Comment by Traehgniw** [comment]
(hi i'm not the original reporter of this but i ran into this issue on the latest version, same mod and everything)

**Comment by ghost** [comment]
New version of JadedLibs fixes this. https://github.com/JadedPacks/Agrarian-Skies/commit/845f0b729fc89b092005e5d3df74ca36f6191c98
