### ISSUE TITLE
Will not even start up, claims duplicate mod

### ISSUE THREAD

**Issue by Traehgniw** [JadedPacks/Agrarian-Skies#25]
## Steps to Reproduce

1. Update from older (pre-rehaul) version
2. Start game. It might complain about a missing dependency for a plugin the first time. If this happens, close game and restart, because it actually does have the dependency.
3. Unlike the dependency error, this one is consistent and persists through multiple cycles of closing and trying to run the game.
4. it claims the duplicate mods are both in minecraft.jar so i deleted the 1.6.4 minecraft.jar and redownloaded. still complaining of double mods.

* Crash Log:
https://pastebin.com/AHaVrGaZ

## Client Information
* Modpack Version: the latest
* Server/LAN/Single Player: Single Player
* Other modpacks are installed on the machine, including one other 1.6.4 modpack, Crash Landing.

**Comment by ghost** [comment]
Resolved as of https://github.com/JadedPacks/Agrarian-Skies/commit/845f0b729fc89b092005e5d3df74ca36f6191c98
