### ISSUE TITLE
Armored Resonant Jetpack not Registering in "Armor-smith" Quest

### ISSUE THREAD

**Issue by mathiasjrg** [JadedPacks/Agrarian-Skies#27]
## Bug Report
In the quest "Armor-Smith" the Resonant Jetpack isn't registering. Manual detecting does not work, and spawning in a jetpack either fully charged, fully depleted or with all 4 mode combinations, doesn't change anything.

## Client Information

* Modpack Version: 4.0.7
* Server/LAN/Single Player: Server + Single-Player

**Comment by ghost** [comment]
Fixed in dev
