### ISSUE TITLE
Where is the multiple rewards opition no party menu?

### ISSUE THREAD

**Issue by artuzim** [JadedPacks/Agrarian-Skies#28]
## Bug Report

don't have the multiple rewards opition
## Steps to Reproduce (for bugs)

1.when change the reward mode dont have the multiple reward opition
2.

## Logs

* Client/Server Log:

## Client Information

* Modpack Version:4.0.5
* Server/LAN/Single Player: LAN

**Comment by ghost** [comment]
This is an intended feature, if you REALLY wish to disable it, change it in the hqm configs.
