### ISSUE TITLE
java.lang.RuntimeException: java.util.ConcurrentModificationException (Server)

### ISSUE THREAD

**Issue by lays24mc** [JadedPacks/Agrarian-Skies#3]
## Steps to Reproduce

1. Start server

When i start my server with this modpack, my server stopps with the issue in the pastebin link. Can you help me? :)
## Logs

* Crash Log: https://pastebin.com/rfjUC8bR

## Client Information

* Modpack Version: 4.0.1
* Server/LAN/Single Player: Server

**Comment by realbun5** [comment]
Also crash while launching the game itself, error: java.util.ConcurrentModificationException.
Crash Log: https://pastebin.com/v1rJPY1x

**Comment by ghost** [comment]
Please see modpack version 4.0.2 ;3 Thanks for the report!
