### ISSUE TITLE
Can't launch Agrarian Skies

### ISSUE THREAD

**Issue by Ceesv23** [JadedPacks/Agrarian-Skies#32]
Downloaden van het bestand is mislukt, omdat de bestandsinhoud anders is dan verwacht.
Naam: argo-2.25_fixed.jar
URL: https://libraries.minecraft.net/argo/argo/2.25_fixed/argo-2.25_fixed.jar
Bestandsnaam op schijf: argo-2.25_fixed.jar
Pad: C:\Users\Cees Veerman\Documents\Curse\Minecraft\Install\libraries\argo\argo\2.25_fixed\argo-2.25_fixed.jar
Bestaat: File

This is what the command prompt says what went wrong, it's in Dutch though.

I tried starting minecraft in 1.6.4 already and don't know if it's because of the new launcher?

**Comment by ghost** [comment]
This is an issue with twitch launcher. It's not something we can fix.
