### ISSUE TITLE
"Three Mile Island" quest doesn't mention sieving

### ISSUE THREAD

**Issue by RundownRhino** [JadedPacks/Agrarian-Skies#33]
In Agrarian Skies **v.4.0.7**, Three Mile Island quest has the following in the description:
![image](https://user-images.githubusercontent.com/52856631/73143145-a2025780-40a7-11ea-9d2c-1c9fc67aaf61.png)
-missing the fact that yellorium is also a sand sieving output.

**Comment by ghost** [comment]
Fixed in dev
