### ISSUE TITLE
"Automated Mining" quest has incorrect power info

### ISSUE THREAD

**Issue by RundownRhino** [JadedPacks/Agrarian-Skies#34]
The quest Automated Mining on the For The Hoarding page claims a single precharger uses 5000RF/t. This is false; in AS it uses 2500RF/t, for a total of 10KRF/t per drill. Pretty sure this has been a bug for a long time.
Config line for the power:
https://github.com/JadedPacks/Agrarian-Skies/blob/3705433cb7c53a01c5f60c120a71503fe80a655a/config/powercrystals/minefactoryreloaded/common.cfg#L330
## Client Information
* Modpack Version: 4.0.7
* Server/LAN/Single Player: server(locally hosted)

**Comment by ghost** [comment]
Fixed in dev
