### ISSUE TITLE
Crash after searching up Mana Bean / Selecting Mana Bean and pressing U

### ISSUE THREAD

**Issue by Hariharakadan** [JadedPacks/Agrarian-Skies#36]
1) Open up the inventory menu
2) Use the search function to find items/recipes
3) Search up "Mana Bean"
4) Select Mana Bean and press U
5) Crash

https://pastebin.com/89Ug4WEk

Agrarian-Skies Minecraft 1.6.4
Single player

**Comment by remclave** [comment]
This is a long-standing bug with the Mana Beans. We cannot fix it and Thaumcraft 4 series is no longer supported by the mod author.
