### ISSUE TITLE
Error applying forge hotfixes

### ISSUE THREAD

**Issue by hozhengzhe** [JadedPacks/Agrarian-Skies#38]
## Steps to Reproduce

1.![image](https://user-images.githubusercontent.com/75124499/100447876-4e5c0280-30ec-11eb-932e-8ae96b372c12.png)

2.

## Logs

* Crash Log:

## Client Information

* Modpack Version:4.1.0 , 4.0.7
* Server/LAN/Single Player:Single Player

**Comment by hozhengzhe** [comment]
Cannot open the modpack anywhere

**Comment by tecrogue** [comment]
Sadly, this is not a pack issue, but a launcher issue. 

Reporting this to curseforge/overwolf is what you would need to do since it is an error on that side.

**Comment by hozhengzhe** [comment]
Thanks for answer my question, i will report to curseforge.
