### ISSUE TITLE
Issue crafting items

### ISSUE THREAD

**Issue by jddrobin** [JadedPacks/Agrarian-Skies#46]
## Bug Report
I attempt to craft an item such as an autonomous activator or a Glacial Precipitator and it shows the item but will not allow me to take the item out of the crafting table.

## Steps to Reproduce (for bugs)

1.Place items for autonomous activator
2.Try to take item out.

## Logs

* Client/Server Log:n/a

## Client Information

* Modpack Version: 4.1.0
* Server/LAN/Single Player:Server

**Comment by tecrogue** [comment]
Issue is missing required information, namely:

Client Information
Modpack Version:
Server/LAN/Single Player:
