### ISSUE TITLE
Server crashed with powercrystalcore

### ISSUE THREAD

**Issue by lays24mc** [JadedPacks/Agrarian-Skies#9]
## Steps to Reproduce

When is start the server, this crasehd with a "NoClassDefFoundError". I don't know what ist the problem. Then this mod is a serverside mod, too. I hope I do not bother you with that. But would like to play with a server :)

## Logs

* Crash Log: https://pastebin.com/38UV7SMh

## Client Information

* Modpack Version: 4.0.5
* Server/LAN/Single Player:

**Comment by ghost** [comment]
Disable JadedMenu and JadedMaps from the server, till we get a fix over on those mods.

**Comment by ghost** [comment]
Fixed as of latest version of mods.
